# Clash 聚合配置
# 订阅地址: https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/clash/config.yaml

rule-providers:
  Qoder:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Clash/Qoder/Qoder.yaml"
    path: ./rules/Qoder.yaml
    interval: 86400

  Trae:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Clash/Trae/Trae.yaml"
    path: ./rules/Trae.yaml
    interval: 86400

  Trae-Telemetry:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Clash/Trae-Telemetry/Trae-Telemetry.yaml"
    path: ./rules/Trae-Telemetry.yaml
    interval: 86400

rules:
  - RULE-SET,Qoder,你的代理策略
  - RULE-SET,Trae,你的代理策略
  - RULE-SET,Trae-Telemetry,REJECT
