# Surge 聚合配置
# 订阅地址: https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/surge/config.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Surge/Qoder/Qoder.conf,你的代理策略
RULE-SET,https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Surge/Trae/Trae.conf,你的代理策略
RULE-SET,https://raw.githubusercontent.com/MorningStar0709/proxy-rules/main/rule/Surge/Trae-Telemetry/Trae-Telemetry.conf,REJECT
